/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
/**
 *
 * @author ACER Aspire5
 */
public class JFrameUtama extends javax.swing.JFrame {
    MysqlMahasiswaService service = new MysqlMahasiswaService();
    
    public JFrameUtama() {
        initComponents();
        updateJList();
    }
    private void updateJList() {
        DefaultListModel<String> idModel = new DefaultListModel<>();
        DefaultListModel<String> namaModel = new DefaultListModel<>();

        List<Mahasiswa> semuaMahasiswa = service.getAll();

        for (Mahasiswa mhs : semuaMahasiswa) {
            idModel.addElement(String.valueOf(mhs.getId()));
            namaModel.addElement(mhs.getName());
        }

        List_ID.setModel(idModel);
        List_Nama.setModel(namaModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        Kelola_Data_Mahasiswa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_ID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_Nama = new javax.swing.JList<>();
        Tombol_Ambil_Semua_Data = new javax.swing.JButton();
        Input_Nama = new javax.swing.JLabel();
        Tambahkan_Text_Nama = new javax.swing.JTextField();
        Tombol_Tambahkan = new javax.swing.JButton();
        Text_ID_Edit = new javax.swing.JTextField();
        Text_Nama_Edit = new javax.swing.JTextField();
        Tombol_Edit = new javax.swing.JButton();
        Tombol_Hapus = new javax.swing.JButton();
        Text_ID_Hapus = new javax.swing.JTextField();
        Text_Nama_Hapus = new javax.swing.JTextField();
        Tombol_Reset_Index = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID.setText("ID");

        NAMA.setText("NAMA");

        Kelola_Data_Mahasiswa.setText("Kelola Data Mahasiswa");

        List_ID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List_ID);

        List_Nama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(List_Nama);

        Tombol_Ambil_Semua_Data.setText("Ambil Semua Data");
        Tombol_Ambil_Semua_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_Ambil_Semua_DataActionPerformed(evt);
            }
        });

        Input_Nama.setText("Nama: ");

        Tombol_Tambahkan.setText("Tambahkan");
        Tombol_Tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_TambahkanActionPerformed(evt);
            }
        });

        Tombol_Edit.setText("Edit");
        Tombol_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_EditActionPerformed(evt);
            }
        });

        Tombol_Hapus.setText("Hapus");
        Tombol_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_HapusActionPerformed(evt);
            }
        });

        Tombol_Reset_Index.setText("Reset index");
        Tombol_Reset_Index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_Reset_IndexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ID)
                        .addGap(34, 34, 34)
                        .addComponent(NAMA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tombol_Reset_Index)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text_ID_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_Nama_Hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tombol_Hapus)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Kelola_Data_Mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tombol_Ambil_Semua_Data)
                            .addComponent(Input_Nama)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tambahkan_Text_Nama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tombol_Tambahkan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Text_ID_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Text_Nama_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tombol_Edit)))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(NAMA)
                    .addComponent(Kelola_Data_Mahasiswa))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Tombol_Ambil_Semua_Data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Input_Nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tambahkan_Text_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tombol_Tambahkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_ID_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Nama_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tombol_Edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tombol_Hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Text_ID_Hapus)
                                .addComponent(Text_Nama_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tombol_Reset_Index)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol_Ambil_Semua_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_Ambil_Semua_DataActionPerformed
        updateJList();
    }//GEN-LAST:event_Tombol_Ambil_Semua_DataActionPerformed

    private void Tombol_TambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_TambahkanActionPerformed
        String nama = Tambahkan_Text_Nama.getText();
        if (nama != null && !nama.trim().isEmpty()) {
            Mahasiswa mhsBaru = new Mahasiswa(nama);
            service.add(mhsBaru);
            updateJList();
            Tambahkan_Text_Nama.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Tombol_TambahkanActionPerformed

    private void Tombol_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_EditActionPerformed
        try {
            int id = Integer.parseInt(Text_ID_Edit.getText());
            String namaBaru = Text_Nama_Edit.getText();
            if (namaBaru != null && !namaBaru.trim().isEmpty()) {
                Mahasiswa mhsUpdate = service.getById(id);
                if (mhsUpdate != null) {
                    mhsUpdate.setName(namaBaru);
                    service.update(mhsUpdate);
                    Text_ID_Edit.setText("");
                    Text_Nama_Edit.setText("");
                    updateJList();
                } else {
                    JOptionPane.showMessageDialog(this, "Mahasiswa dengan ID tersebut tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nama baru tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Tombol_EditActionPerformed

    private void Tombol_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_HapusActionPerformed
        try {
            int id = Integer.parseInt(Text_ID_Hapus.getText());
            service.delete(id);
            Text_ID_Hapus.setText("");
            updateJList();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Tombol_HapusActionPerformed

    private void Tombol_Reset_IndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_Reset_IndexActionPerformed
        service.indexReset();
        updateJList();
    }//GEN-LAST:event_Tombol_Reset_IndexActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Input_Nama;
    private javax.swing.JLabel Kelola_Data_Mahasiswa;
    private javax.swing.JList<String> List_ID;
    private javax.swing.JList<String> List_Nama;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField Tambahkan_Text_Nama;
    private javax.swing.JTextField Text_ID_Edit;
    private javax.swing.JTextField Text_ID_Hapus;
    private javax.swing.JTextField Text_Nama_Edit;
    private javax.swing.JTextField Text_Nama_Hapus;
    private javax.swing.JButton Tombol_Ambil_Semua_Data;
    private javax.swing.JButton Tombol_Edit;
    private javax.swing.JButton Tombol_Hapus;
    private javax.swing.JButton Tombol_Reset_Index;
    private javax.swing.JButton Tombol_Tambahkan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
